### ISSUE TITLE
[space map] sm_careful_alloc::dec() should preserve a block before changing its reference count

### ISSUE THREAD

**Issue by mingnus** [jthornber/thin-provisioning-tools#97]
Otherwise, the input block might be assigned to a shadow block introduced by the subsequent `sm_->dec(b)`, which violates the transaction rule.

It's not easy to reproduce this bug, since that the input block might not be used by the subsequent operations. Possible callstack (based on v0.4.1):
```
#0  bcache::block_cache::get (this=0x818538, index=61662, flags=1, v=...) at block-cache/block_cache.cc:604
#1  0x000000000049d7ce in persistent_data::block_manager<4096u>::write_lock_zero (this=0x818530, location=61662, v=...)
    at ./persistent-data/block.tcc:190
#2  0x000000000049cffd in persistent_data::transaction_manager::shadow (this=0x82a460, orig=3, v=...) at persistent-data/transaction_manager.cc:74
#3  0x0000000000487d53 in (anonymous namespace)::bitmap::insert (this=0x7fffffffd540, b=19, n=1) at persistent-data/space-maps/disk.cc:145
#4  0x00000000004899bd in (anonymous namespace)::sm_disk::insert_bitmap (this=0x82a660, b=19, n=1) at persistent-data/space-maps/disk.cc:537
#5  0x0000000000488762 in (anonymous namespace)::sm_disk::set_count (this=0x82a660, b=19, c=1) at persistent-data/space-maps/disk.cc:327
#6  0x000000000048881a in (anonymous namespace)::sm_disk::inc (this=0x82a660, b=19) at persistent-data/space-maps/disk.cc:343
#7  0x000000000049b6dd in (anonymous namespace)::sm_recursive::flush_ops_ (this=0x82a7b0) at persistent-data/space-maps/recursive.cc:202
#8  0x000000000049b648 in (anonymous namespace)::sm_recursive::flush_ops (this=0x82a7b0) at persistent-data/space-maps/recursive.cc:189
#9  0x000000000049b943 in (anonymous namespace)::sm_recursive::recursing_lock::~recursing_lock (this=0x7fffffffd690, __in_chrg=<optimized out>)
    at persistent-data/space-maps/recursive.cc:239
#10 0x000000000049af78 in (anonymous namespace)::sm_recursive::dec (this=0x82a7b0, b=61662) at persistent-data/space-maps/recursive.cc:127
#11 0x0000000000483d06 in (anonymous namespace)::sm_careful_alloc::dec (this=0x82a840, b=61662) at persistent-data/space-maps/careful_alloc.cc:71
```

Patch for review:
```
diff --git a/persistent-data/space-maps/careful_alloc.cc b/persistent-data/space-maps/careful_alloc.cc
index 4e8560c..018590c 100644
--- a/persistent-data/space-maps/careful_alloc.cc
+++ b/persistent-data/space-maps/careful_alloc.cc
@@ -68,10 +68,10 @@ namespace {
                }
 
                virtual void dec(block_address b) {
-                       sm_->dec(b);
-
-                       if (!sm_->get_count(b))
+                       if (sm_->get_count(b) == 1)
                                mark_freed(b);
+
+                       sm_->dec(b);
                }
 
                virtual maybe_block find_free(span_iterator &it) {
```

**Comment by jthornber** [comment]
Looks good.  Send me a pull request

Thanks.
